base_url = "https://d3c3nt.figbert.com"
title = "d3c3nt :: FIGBERT"
description = "A simple, clean, and flexible theme for personal sites."

generate_feed = true
compile_sass = false

highlight_code = true
highlight_theme = "two-dark"

[extra]
nav = [
  { name = "HOME", path = "/" },
  { name = "CONFIG", path = "/config" },
  { name = "POSTS", path = "/posts/" }
]
icon = "/icon.png"

