name = "d3c3nt"
description = "A simple, clean, and flexible theme for personal sites."
license = "GPLv3"
homepage = "https://github.com/figbert/d3c3nt"
min_version = "0.15.0"
demo = "https://d3c3nt.figbert.com"

[extra]
  d3_nav = []
  d3_icon = ""
  d3_twitter = ""

[author]
  name = "FIGBERT"
  homepage = "https://figbert.com"
