name = "Namal"
description = "A simple, clean, and flexible theme for personal sites."
license = "GPLv3"
homepage = "https://github.com/figbert/namal-zola"
# The minimum version of Zola required
min_version = "0.4.0"
# An optional live demo URL
demo = "https://namal.figbert.com"

# Any variable there can be overriden in the end user `config.toml`
# You don't need to prefix variables by the theme name but as this will
# be merged with user data, some kind of prefix or nesting is preferable
# Use snake_casing to be consistent with the rest of Zola
[extra]

# The theme author info: you!
[author]
name = "FIGBERT"
homepage = "https://figbert.com"

